version: '3.8'

services:
  postgres:
    image: postgres:16
    stop_grace_period: 0s
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-tutor
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
